services:
  web:
    build: .
    environment:
      - NGINX_PORT=80
    ports:
      - 127.0.0.1:8080:80
  json_exporter:
    image: prometheuscommunity/json-exporter:v0.6.0
    networks:
      - internal
    volumes:
      - ./docker/json-exporter.yml:/config.yml:ro
  prometheus:
    image: prom/prometheus:v2.55.0-rc.0
    environment:
      - no_proxy=127.0.0.1,localhost,json_exporter
      - NO_PROXY=127.0.0.1,localhost,json_exporter
    depends_on:
      - json_exporter
    networks:
      - internal
    user: 65534:65534
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/runtime/prometheus:/prometheus
  grafana:
    image: grafana/grafana-enterprise:11.2.1-ubuntu
    depends_on:
      - prometheus
    environment:
      - no_proxy=127.0.0.1,localhost,prometheus
      - NO_PROXY=127.0.0.1,localhost,prometheus
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - internal
    user: 65534:65534
    volumes:
      - ./docker/runtime/grafana:/var/lib/grafana
networks:
  internal:

